# Generated by Django 5.2.15 on 2026-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reminder_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
